### ISSUE TITLE
AttributeError: module 'alpaca_trade_api' has no attribute 'StreamConn'

### ISSUE THREAD

**Issue by Clairewangxiaotong** [alpacahq/example-hftish#15]
Hi,WHEN i run this file,could you correct it ?

**Comment by sshcli** [comment]
@Clairewangxiaotong Alpaca developers will be live tomorrow, you can ask them.

See the Youtube link:
https://alpaca-trading-dashboard.intercom-clicks.com/via/e?ob=OA0C7CLTjUb6SFmJRRkLhntZ6rrRM0lOghk2ROBu5eBa8pbY%2BINBbisBK4YCpvHp&h=37920f945c896ee39e1c790b347ef2f8a7566e7f-p7a9jdob_102275009404445&l=e7331999a95f5382d6dd9afdfa33c8a36649255c-19133950

**Comment by Clairewangxiaotong** [comment]
Thanks for your answer!
But  I am sorry, I did not understand what is the run function doing? could
you write the logic ?
Thanks again!

sshcli ***@***.***> 于2022年10月19日周三 18:12写道：

**Comment by valenticoder** [comment]
have you solved, i am in the same situation now
it says: AttributeError: module 'alpaca_trade_api' has no attribute 'StreamConn'

**Comment by sshcli** [comment]
@Clairewangxiaotong  @valenticoder 

`StreamConn()` has been replaced by `Stream()`

Anyway, you should consider migrate your code to the new `Alpaca-py` API

Regards,

**Comment by leoplct** [comment]
+1 Same issue after 1 year.

```
(example-hftish) me@MacBook-Pro example-hftish % python ./tick_taker.py                     
Traceback (most recent call last):
  File "/example-hftish/./tick_taker.py", line 261, in <module>
    run(args)
  File "/example-hftish/./tick_taker.py", line 133, in run
    conn = tradeapi.StreamConn(**opts)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'alpaca_trade_api' has no attribute 'StreamConn'
```

**Comment by Vejas04** [comment]
Same here.

**Comment by anggarizkia** [comment]
> +1 Masalah yang sama setelah 1 tahun.
> 
> ```
> (example-hftish) me@MacBook-Pro example-hftish % python ./tick_taker.py                     
> Traceback (most recent call last):
>   File "/example-hftish/./tick_taker.py", line 261, in <module>
>     run(args)
>   File "/example-hftish/./tick_taker.py", line 133, in run
>     conn = tradeapi.StreamConn(**opts)
>            ^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'alpaca_trade_api' has no attribute 'StreamConn'
> ```

The error message you're encountering, "AttributeError: module 'alpaca_trade_api' has no attribute 'StreamConn'," suggests that thealpaca_trade_api moduleStreamConn attribute or class

It's possible that thealpaca_trade_api library you have installed has undergone changes or updates, and the StreamConn class may no longer be available or

To resolve this issue, you should first check the documentation oralpaca_trade_api library you

If youStreamConn class has

Here are some general steps you can take:

Check the alpaca_trade_api documentation for the correct way to establish a streaming connection with the latest version of the library.

If StreamConn has been replaced with a different class, update your code to use the new class and follow any new usage patterns

Ensure that you havealpaca_trade_api library installed. You can use pip to upgrade the library:

css
Copy code
pip install --upgrade alpaca-trade-api
Review

By following these steps and referring to the documentation and release notes for the alpaca_trade_api library, you should be able to resolve the AttributeError and update your code to work with the latest version of the library.

**Comment by Vejas04** [comment]
dude literally took it from chatgpt
